### PR TITLE
Fix typo found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by fdomain** [comment]
Hi @DimitriPapadopoulos , thanks for your PR, could you re-format your commit message by following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) please ? This is required to pass the CI, I'll add this to the contributing guidelines soon.

**Comment by DimitriPapadopoulos** [comment]
I think I cannot do that from the GitHub interface which I have used for that commit. I can just add a second commit.

Note that [commitlint](https://github.com/conventional-changelog/commitlint) itself has a bug, it reports two errors where there can be only one (probably the latter):
> ✖   subject may not be empty [subject-empty]
> ✖   type may not be empty [type-empty]

**Comment by fdomain** [comment]
Ok I'm not familiar with the GH interface, but it stills create [a fork in your personal space](https://github.com/DimitriPapadopoulos/ocserv-exporter/tree/DimitriPapadopoulos-patch-1), so I guess you could amend your commit and force push

**Comment by fdomain** [comment]
> Note that [commitlint](https://github.com/conventional-changelog/commitlint) itself has a bug, it reports two errors where there can be only one (probably the latter):
> 
> > heavy_multiplication_x   subject may not be empty [subject-empty]
> > heavy_multiplication_x   type may not be empty [type-empty]

Indeed, I guess it is not able to detect the type/subject as long as there is no ':' in the commit message.

**Comment by DimitriPapadopoulos** [comment]
I had to clone locally on my machine to amend the commit. Should be OK now.

**Comment by fdomain** [comment]
All good, thanks for your contribution!

**Pull request merged**
